/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocialConnection } from '../models/SocialConnection';
import { HttpFile } from '../http/http';

/**
* Social connections of the user
*/
export class ConnectionsList {
    /**
    * List of social connections
    */
    'connections': Array<SocialConnection>;
    /**
    * Whether Discord is connected
    */
    'discordConnected': boolean;
    /**
    * Whether Twitter is connected
    */
    'twitterConnected': boolean;
    /**
    * Whether Telegram is connected
    */
    'telegramConnected': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "connections",
            "baseName": "connections",
            "type": "Array<SocialConnection>",
            "format": ""
        },
        {
            "name": "discordConnected",
            "baseName": "discord_connected",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "twitterConnected",
            "baseName": "twitter_connected",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "telegramConnected",
            "baseName": "telegram_connected",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnectionsList.attributeTypeMap;
    }

    public constructor() {
    }
}
