/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SocialConnection } from '../models/SocialConnection';
import { HttpFile } from '../http/http';

/**
* Create a social connection between the user and the third party service
*/
export class ConnectionResponse {
    /**
    * Success message
    */
    'message': string;
    /**
    * Connection details
    */
    'connection'?: SocialConnection;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "connection",
            "baseName": "connection",
            "type": "SocialConnection",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ConnectionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
