/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeviceWithKey } from '../models/DeviceWithKey';
import { HttpFile } from '../http/http';

/**
* Create a new API key
*/
export class CreateDeviceResponse {
    /**
    * Success message
    */
    'action': string;
    /**
    * The newly created device with API key
    */
    'device': DeviceWithKey;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "DeviceWithKey",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateDeviceResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
