/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserBasic } from '../models/UserBasic';
import { HttpFile } from '../http/http';

/**
* DAO informations.
*/
export class DAO {
    'daoId'?: string;
    'name': string;
    'description': string;
    'ownerId': string;
    'isActive'?: boolean;
    'featured'?: boolean;
    'discordServer'?: string;
    'twitter'?: string;
    'telegram'?: string;
    'instagram'?: string;
    'tiktok'?: string;
    'website'?: string;
    'profilePicture'?: string;
    'treasuryAddress'?: string;
    'modules'?: Array<string>;
    'pubkey'?: string;
    'transaction'?: string;
    'tokenAddress'?: string;
    'governanceModel'?: number;
    'governanceModelName'?: string;
    'votingPowerSystem'?: string;
    'quorumPercentage'?: number;
    'admins'?: Array<UserBasic>;
    'members'?: Array<UserBasic>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "ownerId",
            "baseName": "owner_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "featured",
            "baseName": "featured",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "discordServer",
            "baseName": "discord_server",
            "type": "string",
            "format": ""
        },
        {
            "name": "twitter",
            "baseName": "twitter",
            "type": "string",
            "format": ""
        },
        {
            "name": "telegram",
            "baseName": "telegram",
            "type": "string",
            "format": ""
        },
        {
            "name": "instagram",
            "baseName": "instagram",
            "type": "string",
            "format": ""
        },
        {
            "name": "tiktok",
            "baseName": "tiktok",
            "type": "string",
            "format": ""
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "string",
            "format": ""
        },
        {
            "name": "profilePicture",
            "baseName": "profile_picture",
            "type": "string",
            "format": ""
        },
        {
            "name": "treasuryAddress",
            "baseName": "treasury_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "modules",
            "baseName": "modules",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "pubkey",
            "baseName": "pubkey",
            "type": "string",
            "format": ""
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenAddress",
            "baseName": "token_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "governanceModel",
            "baseName": "governance_model",
            "type": "number",
            "format": ""
        },
        {
            "name": "governanceModelName",
            "baseName": "governance_model_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "votingPowerSystem",
            "baseName": "voting_power_system",
            "type": "string",
            "format": ""
        },
        {
            "name": "quorumPercentage",
            "baseName": "quorum_percentage",
            "type": "number",
            "format": ""
        },
        {
            "name": "admins",
            "baseName": "admins",
            "type": "Array<UserBasic>",
            "format": ""
        },
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<UserBasic>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAO.attributeTypeMap;
    }

    public constructor() {
    }
}
