/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DAOApplicationResponse } from '../models/DAOApplicationResponse';
import { HttpFile } from '../http/http';

/**
* Schema for DAO application list
*/
export class DAOApplicationList {
    /**
    * List of DAO applications
    */
    'applications'?: Array<DAOApplicationResponse>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "applications",
            "baseName": "applications",
            "type": "Array<DAOApplicationResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAOApplicationList.attributeTypeMap;
    }

    public constructor() {
    }
}
