/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Schema for DAO invitation
*/
export class DAOInvitation {
    /**
    * The ID of the user to invite
    */
    'userId': string;
    /**
    * Number of days until the invitation expires (optional)
    */
    'expiresInDays'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresInDays",
            "baseName": "expires_in_days",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAOInvitation.attributeTypeMap;
    }

    public constructor() {
    }
}
