/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Schema for DAO invitation response
*/
export class DAOInvitationResponse {
    /**
    * The action made on the invitation
    */
    'action'?: string;
    /**
    * The ID of the invitation
    */
    'invitationId': string;
    /**
    * The ID of the DAO
    */
    'daoId': string;
    /**
    * The user who sent the invitation
    */
    'inviter': string;
    /**
    * The user who received the invitation
    */
    'invitee': string;
    /**
    * The status of the invitation
    */
    'status': string;
    /**
    * The date and time the invitation expires
    */
    'expiresAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitationId",
            "baseName": "invitation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "inviter",
            "baseName": "inviter",
            "type": "string",
            "format": ""
        },
        {
            "name": "invitee",
            "baseName": "invitee",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return DAOInvitationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
