/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* List of current DAO modules
*/
export class DAOModulesList {
    'modules': Array<string>;
    /**
    * Blockchain account public key for payment
    */
    'pubkey'?: string;
    /**
    * Transaction hash for payment verification
    */
    'transaction'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "modules",
            "baseName": "modules",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "pubkey",
            "baseName": "pubkey",
            "type": "string",
            "format": ""
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAOModulesList.attributeTypeMap;
    }

    public constructor() {
    }
}
