/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Detailed information about a module including payment status
*/
export class DAOModuleDetail {
    /**
    * Module name
    */
    'name': string;
    /**
    * Whether the module is activated for this DAO
    */
    'isActivated': boolean;
    /**
    * Whether the module has been paid for
    */
    'isPaid': boolean;
    /**
    * Payment information if available
    */
    'paymentInfo'?: { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActivated",
            "baseName": "is_activated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isPaid",
            "baseName": "is_paid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "paymentInfo",
            "baseName": "payment_info",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAOModuleDetail.attributeTypeMap;
    }

    public constructor() {
    }
}
