/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DAOModuleDetail } from '../models/DAOModuleDetail';
import { HttpFile } from '../http/http';

/**
* List of current DAO modules with payment information
*/
export class DAOModulesList {
    /**
    * List of current DAO modules with payment information
    */
    'modules'?: Array<DAOModuleDetail>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "modules",
            "baseName": "modules",
            "type": "Array<DAOModuleDetail>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAOModulesList.attributeTypeMap;
    }

    public constructor() {
    }
}
