/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserBasic } from '../models/UserBasic';
import { HttpFile } from '../http/http';

/**
* Schema for DAO user search response
*/
export class DAOUserSearchResponse {
    /**
    * List of users matching the search criteria
    */
    'users': Array<UserBasic>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<UserBasic>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAOUserSearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
