/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DAOUpdate {
    'name'?: string;
    'description'?: string;
    'isActive'?: boolean;
    'discordServer'?: string;
    'twitter'?: string;
    'telegram'?: string;
    'instagram'?: string;
    'tiktok'?: string;
    'website'?: string;
    'profile'?: any | null;
    'banner'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "discordServer",
            "baseName": "discord_server",
            "type": "string",
            "format": ""
        },
        {
            "name": "twitter",
            "baseName": "twitter",
            "type": "string",
            "format": ""
        },
        {
            "name": "telegram",
            "baseName": "telegram",
            "type": "string",
            "format": ""
        },
        {
            "name": "instagram",
            "baseName": "instagram",
            "type": "string",
            "format": ""
        },
        {
            "name": "tiktok",
            "baseName": "tiktok",
            "type": "string",
            "format": ""
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "string",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "any",
            "format": ""
        },
        {
            "name": "banner",
            "baseName": "banner",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DAOUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}
