/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Device } from '../models/Device';
import { HttpFile } from '../http/http';

export class DeviceList {
    /**
    * List of API keys
    */
    'devices'?: Array<Device>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "devices",
            "baseName": "devices",
            "type": "Array<Device>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeviceList.attributeTypeMap;
    }

    public constructor() {
    }
}
