/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Device (API key) informations
*/
export class Device {
    /**
    * Device/API key ID
    */
    'id': string;
    /**
    * Name of the API key
    */
    'deviceName': string;
    /**
    * Masked version of the API key showing first 3 and last 3 characters
    */
    'deviceKey'?: string;
    /**
    * ID of the user who owns this device
    */
    'userId': string;
    /**
    * When the API key was created
    */
    'createdAt': Date;
    /**
    * When the API key was last used
    */
    'lastUsed'?: Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "deviceName",
            "baseName": "device_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "deviceKey",
            "baseName": "device_key",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastUsed",
            "baseName": "last_used",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Device.attributeTypeMap;
    }

    public constructor() {
    }
}
