/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DiscordChannel } from '../models/DiscordChannel';
import { HttpFile } from '../http/http';

/**
* Get multiple Discord channels
*/
export class DiscordChannelsResponse {
    'action': string;
    'channels': Array<DiscordChannel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "channels",
            "baseName": "channels",
            "type": "Array<DiscordChannel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DiscordChannelsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
