/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Discord channel informations
*/
export class DiscordChannel {
    'channelId'?: string;
    'name': string;
    'podId'?: string | null;
    'createdAt'?: Date;
    'lastSyncedAt'?: Date;
    'messageCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "channelId",
            "baseName": "channel_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "podId",
            "baseName": "pod_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastSyncedAt",
            "baseName": "last_synced_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "messageCount",
            "baseName": "message_count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DiscordChannel.attributeTypeMap;
    }

    public constructor() {
    }
}
