/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Discord message informations
*/
export class DiscordMessage {
    'messageId'?: string;
    'channelId': string;
    'username': string;
    'userId': string;
    'text'?: string | null;
    'hasMedia'?: boolean;
    'mediaUrls'?: any | null;
    'createdAt': Date;
    'indexedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageId",
            "baseName": "message_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "channelId",
            "baseName": "channel_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasMedia",
            "baseName": "has_media",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "mediaUrls",
            "baseName": "media_urls",
            "type": "any",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "indexedAt",
            "baseName": "indexed_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return DiscordMessage.attributeTypeMap;
    }

    public constructor() {
    }
}
