/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DiscordMessage } from '../models/DiscordMessage';
import { HttpFile } from '../http/http';

/**
* Get multiple Discord messages
*/
export class DiscordMessagesResponse {
    'action': string;
    'messages': Array<DiscordMessage>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<DiscordMessage>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DiscordMessagesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
