/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Schema for featured toggle response
*/
export class FeaturedResponse {
    'isFeatured'?: boolean;
    /**
    * DateTime when the DAO will be unfeatured, null if not featured
    */
    'featuredUntil'?: any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "isFeatured",
            "baseName": "is_featured",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "featuredUntil",
            "baseName": "featured_until",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FeaturedResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
