/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Schema for featured toggle
*/
export class FeaturedToggle {
    /**
    * Number of days the DAO should remain featured (default: 7, max: 30)
    */
    'days'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "days",
            "baseName": "days",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FeaturedToggle.attributeTypeMap;
    }

    public constructor() {
    }
}
