/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GovernanceModel } from '../models/GovernanceModel';
import { HttpFile } from '../http/http';

/**
* List of available governance models
*/
export class GovernanceModelsList {
    'models': Array<GovernanceModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "models",
            "baseName": "models",
            "type": "Array<GovernanceModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GovernanceModelsList.attributeTypeMap;
    }

    public constructor() {
    }
}
