/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* DAO governance settings
*/
export class Governance {
    'daoId'?: string;
    'governanceModel': number;
    'governanceModelName'?: string;
    'votingPowerSystem': GovernanceVotingPowerSystemEnum;
    'councilEntryCondition'?: GovernanceCouncilEntryConditionEnum;
    'councilEntryThreshold'?: number;
    'daoEntryCondition': GovernanceDaoEntryConditionEnum;
    'daoEntryThreshold'?: number;
    'quorumPercentage': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "governanceModel",
            "baseName": "governance_model",
            "type": "number",
            "format": ""
        },
        {
            "name": "governanceModelName",
            "baseName": "governance_model_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "votingPowerSystem",
            "baseName": "voting_power_system",
            "type": "GovernanceVotingPowerSystemEnum",
            "format": ""
        },
        {
            "name": "councilEntryCondition",
            "baseName": "council_entry_condition",
            "type": "GovernanceCouncilEntryConditionEnum",
            "format": ""
        },
        {
            "name": "councilEntryThreshold",
            "baseName": "council_entry_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "daoEntryCondition",
            "baseName": "dao_entry_condition",
            "type": "GovernanceDaoEntryConditionEnum",
            "format": ""
        },
        {
            "name": "daoEntryThreshold",
            "baseName": "dao_entry_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "quorumPercentage",
            "baseName": "quorum_percentage",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Governance.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum GovernanceVotingPowerSystemEnum {
    Defined = 'Defined',
    Token = 'Token',
    OneOne = 'OneOne',
    Quadratic = 'Quadratic'
}
export enum GovernanceCouncilEntryConditionEnum {
    Election = 'Election',
    Token = 'Token',
    Closed = 'Closed',
    Open = 'Open'
}
export enum GovernanceDaoEntryConditionEnum {
    Candidature = 'Candidature',
    Token = 'Token',
    Closed = 'Closed',
    Open = 'Open'
}

