/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* New user information
*/
export class InputUpdateUser {
    /**
    * New username of the user
    */
    'username'?: string;
    /**
    * New email of the user
    */
    'email'?: string;
    /**
    * New display name of the user
    */
    'memberName'?: string;
    /**
    * New profile picture of the user
    */
    'profilePicture'?: HttpFile;
    /**
    * New Discord username of the user
    */
    'discordUsername'?: string;
    /**
    * New Twitter username of the user
    */
    'twitterUsername'?: string;
    /**
    * New Telegram username of the user
    */
    'telegramUsername'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "memberName",
            "baseName": "member_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "profilePicture",
            "baseName": "profile_picture",
            "type": "HttpFile",
            "format": "binary"
        },
        {
            "name": "discordUsername",
            "baseName": "discord_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "twitterUsername",
            "baseName": "twitter_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "telegramUsername",
            "baseName": "telegram_username",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InputUpdateUser.attributeTypeMap;
    }

    public constructor() {
    }
}
