/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Input information needed to create DAO.
*/
export class InputCreateDAO {
    'name': string;
    'description': string;
    'discordServer'?: string;
    'twitter'?: string;
    'telegram'?: string;
    'instagram'?: string;
    'tiktok'?: string;
    'website'?: string;
    'tokenAddress': string;
    /**
    * Governance model (1-8): 1-Enlightened Dictatorship, 2-Assisted Dictatorship, 3-Hybrid Enterprise, 4-Listed Company, 5-Social Enterprise, 6-Association, 7-Semi-decentralized Organization, 8-Decentralized Pure
    */
    'governanceModel'?: number;
    /**
    * Voting power system: Defined, Token, OneOne, Quadratic
    */
    'votingPowerSystem'?: InputCreateDAOVotingPowerSystemEnum;
    /**
    * Quorum percentage required for proposals (1-100)
    */
    'quorumPercentage'?: number;
    'profile'?: HttpFile;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "discordServer",
            "baseName": "discord_server",
            "type": "string",
            "format": ""
        },
        {
            "name": "twitter",
            "baseName": "twitter",
            "type": "string",
            "format": ""
        },
        {
            "name": "telegram",
            "baseName": "telegram",
            "type": "string",
            "format": ""
        },
        {
            "name": "instagram",
            "baseName": "instagram",
            "type": "string",
            "format": ""
        },
        {
            "name": "tiktok",
            "baseName": "tiktok",
            "type": "string",
            "format": ""
        },
        {
            "name": "website",
            "baseName": "website",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenAddress",
            "baseName": "token_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "governanceModel",
            "baseName": "governance_model",
            "type": "number",
            "format": ""
        },
        {
            "name": "votingPowerSystem",
            "baseName": "voting_power_system",
            "type": "InputCreateDAOVotingPowerSystemEnum",
            "format": ""
        },
        {
            "name": "quorumPercentage",
            "baseName": "quorum_percentage",
            "type": "number",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "HttpFile",
            "format": "binary"
        }    ];

    static getAttributeTypeMap() {
        return InputCreateDAO.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum InputCreateDAOVotingPowerSystemEnum {
    Defined = 'Defined',
    Token = 'Token',
    OneOne = 'OneOne',
    Quadratic = 'Quadratic'
}

