/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProposalAction } from '../models/ProposalAction';
import { HttpFile } from '../http/http';

/**
* Input information needed to create a Proposal
*/
export class InputCreateProposal {
    'name': string;
    'description': string;
    'daoId': string;
    'podId'?: string | null;
    'startTime': Date;
    'endTime': Date;
    'actions'?: Array<ProposalAction> | null;
    'pubkey': string;
    'transaction': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "podId",
            "baseName": "pod_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "actions",
            "baseName": "actions",
            "type": "Array<ProposalAction>",
            "format": ""
        },
        {
            "name": "pubkey",
            "baseName": "pubkey",
            "type": "string",
            "format": ""
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InputCreateProposal.attributeTypeMap;
    }

    public constructor() {
    }
}
