/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Update DAO governance settings
*/
export class InputUpdateGovernance {
    'governanceModel'?: number;
    'votingPowerSystem'?: InputUpdateGovernanceVotingPowerSystemEnum;
    'councilEntryCondition'?: InputUpdateGovernanceCouncilEntryConditionEnum;
    'councilEntryThreshold'?: number;
    'daoEntryCondition'?: InputUpdateGovernanceDaoEntryConditionEnum;
    'daoEntryThreshold'?: number;
    'quorumPercentage'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "governanceModel",
            "baseName": "governance_model",
            "type": "number",
            "format": ""
        },
        {
            "name": "votingPowerSystem",
            "baseName": "voting_power_system",
            "type": "InputUpdateGovernanceVotingPowerSystemEnum",
            "format": ""
        },
        {
            "name": "councilEntryCondition",
            "baseName": "council_entry_condition",
            "type": "InputUpdateGovernanceCouncilEntryConditionEnum",
            "format": ""
        },
        {
            "name": "councilEntryThreshold",
            "baseName": "council_entry_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "daoEntryCondition",
            "baseName": "dao_entry_condition",
            "type": "InputUpdateGovernanceDaoEntryConditionEnum",
            "format": ""
        },
        {
            "name": "daoEntryThreshold",
            "baseName": "dao_entry_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "quorumPercentage",
            "baseName": "quorum_percentage",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InputUpdateGovernance.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum InputUpdateGovernanceVotingPowerSystemEnum {
    Defined = 'Defined',
    Token = 'Token',
    OneOne = 'OneOne',
    Quadratic = 'Quadratic'
}
export enum InputUpdateGovernanceCouncilEntryConditionEnum {
    Election = 'Election',
    Token = 'Token',
    Closed = 'Closed',
    Open = 'Open'
}
export enum InputUpdateGovernanceDaoEntryConditionEnum {
    Application = 'Application',
    Token = 'Token',
    Closed = 'Closed',
    Open = 'Open'
}

