/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Permission } from '../models/Permission';
import { HttpFile } from '../http/http';

/**
* List of permissions
*/
export class PermissionListResponse {
    'permissions': Array<Permission>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<Permission>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PermissionListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
