/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DiscordChannel } from '../models/DiscordChannel';
import { HttpFile } from '../http/http';

/**
* POD informations
*/
export class POD {
    'podId'?: string;
    'daoId': string;
    'name': string;
    'description': string;
    'isActive'?: boolean;
    'createdAt'?: Date;
    'discordChannels'?: Array<DiscordChannel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "podId",
            "baseName": "pod_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "discordChannels",
            "baseName": "discord_channels",
            "type": "Array<DiscordChannel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return POD.attributeTypeMap;
    }

    public constructor() {
    }
}
