/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Proposal } from '../models/Proposal';
import { HttpFile } from '../http/http';

/**
* List POD proposals
*/
export class PodProposalListResponse {
    'podId': string;
    'proposals': Array<Proposal>;
    'totalCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "podId",
            "baseName": "pod_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "proposals",
            "baseName": "proposals",
            "type": "Array<Proposal>",
            "format": ""
        },
        {
            "name": "totalCount",
            "baseName": "total_count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PodProposalListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
