/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Proposal } from '../models/Proposal';
import { HttpFile } from '../http/http';

/**
* Create/Update a Proposal
*/
export class ProposalSchemaResponse {
    'action': string;
    'proposal': Proposal;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "proposal",
            "baseName": "proposal",
            "type": "Proposal",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProposalSchemaResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
