/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Proposal } from '../models/Proposal';
import { HttpFile } from '../http/http';

/**
* Proposal vote response
*/
export class ProposalVoteResponse {
    'action': string;
    'voteStatus': ProposalVoteResponseVoteStatusEnum;
    'proposal': Proposal;
    'forVotesCount': number;
    'againstVotesCount': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "voteStatus",
            "baseName": "vote_status",
            "type": "ProposalVoteResponseVoteStatusEnum",
            "format": ""
        },
        {
            "name": "proposal",
            "baseName": "proposal",
            "type": "Proposal",
            "format": ""
        },
        {
            "name": "forVotesCount",
            "baseName": "for_votes_count",
            "type": "number",
            "format": ""
        },
        {
            "name": "againstVotesCount",
            "baseName": "against_votes_count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProposalVoteResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProposalVoteResponseVoteStatusEnum {
    None = 'none',
    For = 'for',
    Against = 'against'
}

