/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Proposal action
*/
export class ProposalAction {
    'type': ProposalActionTypeEnum;
    'data': { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ProposalActionTypeEnum",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProposalAction.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProposalActionTypeEnum {
    AddMember = 'ADD_MEMBER',
    RemoveMember = 'REMOVE_MEMBER',
    UpdateDao = 'UPDATE_DAO',
    UpdateDaoGovernance = 'UPDATE_DAO_GOVERNANCE',
    CreatePod = 'CREATE_POD'
}

