/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Permission } from '../models/Permission';
import { Role } from '../models/Role';
import { HttpFile } from '../http/http';

/**
* Assign/Remove permission to/from role response
*/
export class RolePermissionResponse {
    'action': string;
    'role': Role;
    'permission': Permission;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "Role",
            "format": ""
        },
        {
            "name": "permission",
            "baseName": "permission",
            "type": "Permission",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RolePermissionResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
