/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Information for assigning a permission to a role
*/
export class RolePermissionAssignment {
    'roleId': string;
    'permissionId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "roleId",
            "baseName": "role_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "permissionId",
            "baseName": "permission_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RolePermissionAssignment.attributeTypeMap;
    }

    public constructor() {
    }
}
