/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Social connection informations
*/
export class SocialConnection {
    /**
    * Social provider name (discord, twitter, telegram)
    */
    'provider': string;
    /**
    * User ID from the provider
    */
    'providerUserId': string;
    /**
    * Username from the provider
    */
    'providerUsername': string;
    /**
    * When the connection was established
    */
    'connectedAt'?: Date;
    /**
    * When the connection was last updated
    */
    'updatedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerUserId",
            "baseName": "provider_user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "providerUsername",
            "baseName": "provider_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "connectedAt",
            "baseName": "connected_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return SocialConnection.attributeTypeMap;
    }

    public constructor() {
    }
}
