/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Token informations
*/
export class Token {
    'tokenId'?: string;
    'walletAddress'?: string;
    'tokenMint'?: string;
    'balance'?: number;
    'lastUpdated'?: Date;
    'symbol'?: string;
    'decimals'?: number;
    'price'?: number;
    'priceChangePercentage'?: number;
    'photoUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tokenId",
            "baseName": "token_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletAddress",
            "baseName": "wallet_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenMint",
            "baseName": "token_mint",
            "type": "string",
            "format": ""
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastUpdated",
            "baseName": "last_updated",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "string",
            "format": ""
        },
        {
            "name": "decimals",
            "baseName": "decimals",
            "type": "number",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "priceChangePercentage",
            "baseName": "price_change_percentage",
            "type": "number",
            "format": ""
        },
        {
            "name": "photoUrl",
            "baseName": "photo_url",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Token.attributeTypeMap;
    }

    public constructor() {
    }
}
