/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Input information needed to create a Transfer
*/
export class TransferCreate {
    'daoId': string;
    'tokenId': string;
    'fromAddress': string;
    'toAddress': string;
    'amount': number;
    'timestamp'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "tokenId",
            "baseName": "token_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "fromAddress",
            "baseName": "from_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "toAddress",
            "baseName": "to_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return TransferCreate.attributeTypeMap;
    }

    public constructor() {
    }
}
