/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Transfer } from '../models/Transfer';
import { HttpFile } from '../http/http';

/**
* Create/Update a Transfer
*/
export class TransferSchemaResponse {
    'action': string;
    'transfer': Transfer;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "transfer",
            "baseName": "transfer",
            "type": "Transfer",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TransferSchemaResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
