/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserApplication } from '../models/UserApplication';
import { HttpFile } from '../http/http';

/**
* Response containing user\'s DAO applications
*/
export class UserApplicationResponse {
    /**
    * List of user\'s DAO applications
    */
    'applications'?: Array<UserApplication>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "applications",
            "baseName": "applications",
            "type": "Array<UserApplication>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserApplicationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
