/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { UserInvitation } from '../models/UserInvitation';
import { HttpFile } from '../http/http';

/**
* Response containing user\'s DAO invitations
*/
export class UserInvitationsResponse {
    /**
    * List of invitations
    */
    'invitations'?: Array<UserInvitation>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "invitations",
            "baseName": "invitations",
            "type": "Array<UserInvitation>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserInvitationsResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
