/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* User\'s DAO application information
*/
export class UserApplication {
    /**
    * Unique application identifier
    */
    'applicationId'?: string;
    /**
    * ID of the DAO this application is for
    */
    'daoId'?: string;
    /**
    * Name of the DAO this application is for
    */
    'daoName'?: string;
    /**
    * Username of the user who applied
    */
    'user'?: string;
    /**
    * Status of the application
    */
    'status'?: string;
    /**
    * Message from the applicant
    */
    'message'?: string;
    /**
    * Response from the DAO admin
    */
    'response'?: string;
    /**
    * When the application was created
    */
    'createdAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "applicationId",
            "baseName": "application_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "daoName",
            "baseName": "dao_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserApplication.attributeTypeMap;
    }

    public constructor() {
    }
}
