/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Result of checking if a user has a role
*/
export class UserRoleCheck {
    'hasRole': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasRole",
            "baseName": "has_role",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserRoleCheck.attributeTypeMap;
    }

    public constructor() {
    }
}
