/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from '../models/User';
import { HttpFile } from '../http/http';

/**
* Schema for user search response
*/
export class UserSearchResponse {
    /**
    * List of users matching the search criteria
    */
    'users': Array<User>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "users",
            "baseName": "users",
            "type": "Array<User>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserSearchResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
