/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PodBasic } from '../models/PodBasic';
import { HttpFile } from '../http/http';

/**
* Basic user information for nested DAO relationships
*/
export class UserBasic {
    'userId'?: string;
    'username'?: string;
    'profilePicture'?: string;
    'walletAddress'?: string;
    'pods'?: Array<PodBasic>;
    'discordUsername'?: string;
    'twitterUsername'?: string;
    'telegramUsername'?: string;
    /**
    * Last interaction timestamp
    */
    'lastInteraction'?: Date;
    /**
    * Last login timestamp
    */
    'lastLogin'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "profilePicture",
            "baseName": "profile_picture",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletAddress",
            "baseName": "wallet_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "pods",
            "baseName": "pods",
            "type": "Array<PodBasic>",
            "format": ""
        },
        {
            "name": "discordUsername",
            "baseName": "discord_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "twitterUsername",
            "baseName": "twitter_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "telegramUsername",
            "baseName": "telegram_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastInteraction",
            "baseName": "last_interaction",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastLogin",
            "baseName": "last_login",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return UserBasic.attributeTypeMap;
    }

    public constructor() {
    }
}
