/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* DAO invitation information
*/
export class UserInvitation {
    /**
    * Unique invitation identifier
    */
    'invitationId'?: string;
    /**
    * ID of the DAO this invitation is for
    */
    'daoId'?: string;
    /**
    * Name of the DAO
    */
    'daoName'?: string;
    /**
    * ID of the user who sent the invitation
    */
    'inviterId'?: string;
    /**
    * Username of the user who sent the invitation
    */
    'inviterUsername'?: string;
    /**
    * Status of the invitation (pending, accepted, declined, expired)
    */
    'status'?: string;
    /**
    * When the invitation was created
    */
    'createdAt'?: Date;
    /**
    * When the invitation expires (if applicable)
    */
    'expiresAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "invitationId",
            "baseName": "invitation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "daoId",
            "baseName": "dao_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "daoName",
            "baseName": "dao_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "inviterId",
            "baseName": "inviter_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "inviterUsername",
            "baseName": "inviter_username",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return UserInvitation.attributeTypeMap;
    }

    public constructor() {
    }
}
