/**
 * DAO-API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* User informations.
*/
export class User {
    /**
    * Unique user identifier
    */
    'userId'?: string;
    /**
    * Username of the user
    */
    'username'?: string;
    /**
    * Wallet address of the user
    */
    'walletAddress'?: string;
    /**
    * Email of the user
    */
    'email'?: any | null;
    /**
    * Display name of the user
    */
    'memberName'?: any | null;
    /**
    * Profile picture of the user
    */
    'profilePicture'?: any | null;
    /**
    * Discord username of the user
    */
    'discordUsername'?: any | null;
    /**
    * Twitter username of the user
    */
    'twitterUsername'?: any | null;
    /**
    * Telegram username of the user
    */
    'telegramUsername'?: any | null;
    /**
    * Last login timestamp
    */
    'lastLogin'?: Date;
    /**
    * Last interaction timestamp
    */
    'lastInteraction'?: Date;
    /**
    * Whether the email is verified
    */
    'emailVerified'?: boolean;
    /**
    * Whether the user is active
    */
    'isActive'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "walletAddress",
            "baseName": "wallet_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "any",
            "format": ""
        },
        {
            "name": "memberName",
            "baseName": "member_name",
            "type": "any",
            "format": ""
        },
        {
            "name": "profilePicture",
            "baseName": "profile_picture",
            "type": "any",
            "format": ""
        },
        {
            "name": "discordUsername",
            "baseName": "discord_username",
            "type": "any",
            "format": ""
        },
        {
            "name": "twitterUsername",
            "baseName": "twitter_username",
            "type": "any",
            "format": ""
        },
        {
            "name": "telegramUsername",
            "baseName": "telegram_username",
            "type": "any",
            "format": ""
        },
        {
            "name": "lastLogin",
            "baseName": "last_login",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "lastInteraction",
            "baseName": "last_interaction",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "emailVerified",
            "baseName": "email_verified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}
